### ISSUE TITLE
How to update an already running coinmaker?

### ISSUE THREAD

**Issue by kxygk** [sbhackerspace/CoinMaker#4]
(can't reach you on Skype pancakeface)

I'm trying to update Gordon's webpage. Made a small change (just for testing) to the HTML and tried running WebFrontEnd.py - but the thing gets angry

```
$ ./WebFrontEnd.py
* Running on http://0.0.0.0:5001/
Traceback (most recent call last):
File "./WebFrontEnd.py", line 72, in
app.run(host='0.0.0.0', port=5001, debug=True)
File "/usr/lib/python2.7/dist-packages/flask/app.py", line 772, in run
run_simple(host, port, self, **options)
File "/usr/lib/python2.7/dist-packages/werkzeug/serving.py", line 706, in run_simple
test_socket.bind((hostname, port))
File "/usr/lib/python2.7/socket.py", line 224, in meth
return getattr(self._sock,name)(*args)
socket.error: [Errno 98] Address already in use
```

What am I doing wrong?

**Comment by elimisteve** [comment]
> [Errno 98] Address already in use

Sounds like you're already running some other program on port 5001?

**Comment by dloman** [comment]
yeah you @elimisteve sounds like you are right. @geokon-gh you need to kill the current web front end before you run the updated one

**Comment by kxygk** [comment]
just kill the process...? Will the script restart it? (I'm guessing that's what app.run(..) does)
I'm going to test it out on a testing server and get back to you

Thanks for the feedback guys
